apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-dev-deployment
  namespace: sjb-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      type: back
  template:
    metadata:
      labels:
        type: back
    spec:
      containers:
      - name: container
        image: ddarahakit2023/back:latest
        command: ["/bin/sh", "-ec", "python manage.py migrate && gunicorn config.wsgi --bind 0.0.0.0:8000"]
        envFrom:
          - configMapRef:
              name: backend-cm
        ports:
        - containerPort: 8000